# Generated by Django 4.2.3 on 2023-08-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registation',
            fields=[
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=90)),
                ('address', models.TextField()),
            ],
        ),
    ]
