# Generated by Django 4.2.1 on 2023-08-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_delete_registation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
